language: node_js
node_js:
  - "5.1"
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
env:
  - ZMQ="4.1.3" SODIUM="1.0.5"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8
      - uuid-dev

before_install:
  - travis_before_install

install: env LD_LIBRARY_PATH=$LDHACK/lib LD_RUN_PATH=$LDHACK/lib PKG_CONFIG_PATH=$LDHACK/lib/pkgconfig LDFLAGS=-L$LDHACK/lib CFLAGS=-I$LDHACK/lib/include npm install

cache:
  directories:
    - node_modules
    - $HOME/.electron
